In [2]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

In [4]:
i=pd.read_csv("/content/IRIS.csv")
i

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [5]:
i.shape

(150, 5)

In [6]:
i.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [7]:
i.info

<bound method DataFrame.info of      sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]>

In [55]:
print("Display first 10 records")
i.head(10)

Display first 10 records

,sepal_length,sepal_width,petal_length,petal_width,species,total_size
0,5.1,3.5,1.4,0.2,Iris-setosa,6.5
1,4.9,3.0,1.4,0.2,Iris-setosa,6.3
2,4.7,3.2,1.3,0.2,Iris-setosa,6.0
3,4.6,3.1,1.5,0.2,Iris-setosa,6.1
4,5.0,3.6,1.4,0.2,Iris-setosa,6.4
5,5.4,3.9,1.7,0.4,Iris-setosa,7.1
6,4.6,3.4,1.4,0.3,Iris-setosa,6.0
7,5.0,3.4,1.5,0.2,Iris-setosa,6.5
8,4.4,2.9,1.4,0.2,Iris-setosa,5.8
9,4.9,3.1,1.5,0.1,Iris-setosa,6.4

In [56]:
print("unique species")
i["species"].unique

unique species

<bound method Series.unique of 0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: object>

In [57]:
print("count flowers in each species")
i['species'].value_counts()

count flowers in each species

species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [58]:
result =i.groupby('species')['petal_length'].mean()
print("average petal length for each species  ")
result

average petal length for each species

species
Iris-setosa        1.464
Iris-versicolor    4.260
Iris-virginica     5.552
Name: petal_length, dtype: float64

In [59]:
max_sepal_length = i['sepal_length'].max()
print("max_sepal_length : ",max_sepal_length)

max_sepal_length :  7.9

In [60]:
max_flower = i[i['sepal_length'] == i['sepal_length'].max()]
max_flower

,sepal_length,sepal_width,petal_length,petal_width,species,total_size
131,7.9,3.8,6.4,2.0,Iris-virginica,14.3

In [61]:
sort = i.sort_values(by='petal_width',ascending=False)
print("Sort by petal width descending  ")
sort

Sort by petal width descending

,sepal_length,sepal_width,petal_length,petal_width,species,total_size
144,6.7,3.3,5.7,2.5,Iris-virginica,12.4
109,7.2,3.6,6.1,2.5,Iris-virginica,13.3
100,6.3,3.3,6.0,2.5,Iris-virginica,12.3
114,5.8,2.8,5.1,2.4,Iris-virginica,10.9
136,6.3,3.4,5.6,2.4,Iris-virginica,11.9
...,...,...,...,...,...,...
9,4.9,3.1,1.5,0.1,Iris-setosa,6.4
12,4.8,3.0,1.4,0.1,Iris-setosa,6.2
32,5.2,4.1,1.5,0.1,Iris-setosa,6.7
34,4.9,3.1,1.5,0.1,Iris-setosa,6.4
37,4.9,3.1,1.5,0.1,Iris-setosa,6.4

In [62]:
filter=i[i["petal_length"]>5]
print("Filter flowers with petal_length greater than 5 are ")
filter

Filter flowers with petal_length greater than 5 are

,sepal_length,sepal_width,petal_length,petal_width,species,total_size
83,6.0,2.7,5.1,1.6,Iris-versicolor,11.1
100,6.3,3.3,6.0,2.5,Iris-virginica,12.3
101,5.8,2.7,5.1,1.9,Iris-virginica,10.9
102,7.1,3.0,5.9,2.1,Iris-virginica,13.0
103,6.3,2.9,5.6,1.8,Iris-virginica,11.9
104,6.5,3.0,5.8,2.2,Iris-virginica,12.3
105,7.6,3.0,6.6,2.1,Iris-virginica,14.2
107,7.3,2.9,6.3,1.8,Iris-virginica,13.6
108,6.7,2.5,5.8,1.8,Iris-virginica,12.5
109,7.2,3.6,6.1,2.5,Iris-virginica,13.3
110,6.5,3.2,5.1,2.0,Iris-virginica,11.6
111,6.4,2.7,5.3,1.9,Iris-virginica,11.7
112,6.8,3.0,5.5,2.1,Iris-virginica,12.3
114,5.8,2.8,5.1,2.4,Iris-virginica,10.9
115,6.4,3.2,5.3,2.3,Iris-virginica,11.7
116,6.5,3.0,5.5,1.8,Iris-virginica,12.0
117,7.7,3.8,6.7,2.2,Iris-virginica,14.4
118,7.7,2.6,6.9,2.3,Iris-virginica,14.6
120,6.9,3.2,5.7,2.3,Iris-virginica,12.6
122,7.7,2.8,6.7,2.0,Iris-virginica,14.4
124,6.7,3.3,5.7,2.1,Iris-virginica,12.4
125,7.2,3.2,6.0,1.8,Iris-virginica,13.2
128,6.4,2.8,5.6,2.1,Iris-virginica,12.0
129,7.2,3.0,5.8,1.6,Iris-virginica,13.0
130,7.4,2.8,6.1,1.9,Iris-virginica,13.5
131,7.9,3.8,6.4,2.0,Iris-virginica,14.3
132,6.4,2.8,5.6,2.2,Iris-virginica,12.0
133,6.3,2.8,5.1,1.5,Iris-virginica,11.4
134,6.1,2.6,5.6,1.4,Iris-virginica,11.7
135,7.7,3.0,6.1,2.3,Iris-virginica,13.8
136,6.3,3.4,5.6,2.4,Iris-virginica,11.9
137,6.4,3.1,5.5,1.8,Iris-virginica,11.9
139,6.9,3.1,5.4,2.1,Iris-virginica,12.3
140,6.7,3.1,5.6,2.4,Iris-virginica,12.3
141,6.9,3.1,5.1,2.3,Iris-virginica,12.0
142,5.8,2.7,5.1,1.9,Iris-virginica,10.9
143,6.8,3.2,5.9,2.3,Iris-virginica,12.7
144,6.7,3.3,5.7,2.5,Iris-virginica,12.4
145,6.7,3.0,5.2,2.3,Iris-virginica,11.9
147,6.5,3.0,5.2,2.0,Iris-virginica,11.7
148,6.2,3.4,5.4,2.3,Iris-virginica,11.6
149,5.9,3.0,5.1,1.8,Iris-virginica,11.0

In [65]:
print("Adding new column as total_size")
i["total_size"]=i["sepal_length"]+i["petal_length"]
i

Adding new column as total_size

,sepal_length,sepal_width,petal_length,petal_width,species,total_size
0,5.1,3.5,1.4,0.2,Iris-setosa,6.5
1,4.9,3.0,1.4,0.2,Iris-setosa,6.3
2,4.7,3.2,1.3,0.2,Iris-setosa,6.0
3,4.6,3.1,1.5,0.2,Iris-setosa,6.1
4,5.0,3.6,1.4,0.2,Iris-setosa,6.4
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,11.9
146,6.3,2.5,5.0,1.9,Iris-virginica,11.3
147,6.5,3.0,5.2,2.0,Iris-virginica,11.7
148,6.2,3.4,5.4,2.3,Iris-virginica,11.6
149,5.9,3.0,5.1,1.8,Iris-virginica,11.0

In [66]:
i.to_csv("filtered iris data.csv")
print("File saved succesfully")
i

File saved succesfully

,sepal_length,sepal_width,petal_length,petal_width,species,total_size
0,5.1,3.5,1.4,0.2,Iris-setosa,6.5
1,4.9,3.0,1.4,0.2,Iris-setosa,6.3
2,4.7,3.2,1.3,0.2,Iris-setosa,6.0
3,4.6,3.1,1.5,0.2,Iris-setosa,6.1
4,5.0,3.6,1.4,0.2,Iris-setosa,6.4
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,11.9
146,6.3,2.5,5.0,1.9,Iris-virginica,11.3
147,6.5,3.0,5.2,2.0,Iris-virginica,11.7
148,6.2,3.4,5.4,2.3,Iris-virginica,11.6
149,5.9,3.0,5.1,1.8,Iris-virginica,11.0

In [67]:
import numpy as np

In [68]:
petal_array = i['petal_length'].to_numpy()
print("petal array ")
petal_array

petal array

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.6, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1,
       5.9, 5.7, 5.2, 5. , 5.2, 5.4, 5.1])

In [69]:
print("Mean:", np.mean(petal_array))

Mean: 3.758666666666666

In [70]:
print("Median:", np.median(petal_array))

Median: 4.35

In [71]:
print("Standard Deviation:", np.std(petal_array))

Standard Deviation: 1.7585291834055212

In [72]:
print("maximum value of petal array")
petal_array.max()

maximum value of petal array

np.float64(6.9)

In [73]:
print("minimum value of petal array")
petal_array.min()

minimum value of petal array

np.float64(1.0)

In [74]:
print("Max:", np.max(petal_array))
print("Min:", np.min(petal_array))

Max: 6.9
Min: 1.0

In [75]:
normalized = (petal_array - np.min(petal_array)) / (np.max(petal_array) - np.min(petal_array))

print(normalized)

[0.06779661 0.06779661 0.05084746 0.08474576 0.06779661 0.11864407
 0.06779661 0.08474576 0.06779661 0.08474576 0.08474576 0.10169492
 0.06779661 0.01694915 0.03389831 0.08474576 0.05084746 0.06779661
 0.11864407 0.08474576 0.11864407 0.08474576 0.         0.11864407
 0.15254237 0.10169492 0.10169492 0.08474576 0.06779661 0.10169492
 0.10169492 0.08474576 0.08474576 0.06779661 0.08474576 0.03389831
 0.05084746 0.08474576 0.05084746 0.08474576 0.05084746 0.05084746
 0.05084746 0.10169492 0.15254237 0.06779661 0.10169492 0.06779661
 0.08474576 0.06779661 0.62711864 0.59322034 0.66101695 0.50847458
 0.61016949 0.59322034 0.62711864 0.38983051 0.61016949 0.49152542
 0.42372881 0.54237288 0.50847458 0.62711864 0.44067797 0.57627119
 0.59322034 0.52542373 0.59322034 0.49152542 0.6440678  0.50847458
 0.66101695 0.62711864 0.55932203 0.57627119 0.6440678  0.6779661
 0.59322034 0.42372881 0.47457627 0.45762712 0.49152542 0.69491525
 0.59322034 0.59322034 0.62711864 0.57627119 0.52542373 0.50847458
 0.57627119 0.61016949 0.50847458 0.38983051 0.54237288 0.54237288
 0.54237288 0.55932203 0.33898305 0.52542373 0.84745763 0.69491525
 0.83050847 0.77966102 0.81355932 0.94915254 0.59322034 0.89830508
 0.81355932 0.86440678 0.69491525 0.72881356 0.76271186 0.6779661
 0.69491525 0.72881356 0.76271186 0.96610169 1.         0.6779661
 0.79661017 0.66101695 0.96610169 0.66101695 0.79661017 0.84745763
 0.6440678  0.66101695 0.77966102 0.81355932 0.86440678 0.91525424
 0.77966102 0.69491525 0.77966102 0.86440678 0.77966102 0.76271186
 0.6440678  0.74576271 0.77966102 0.69491525 0.69491525 0.83050847
 0.79661017 0.71186441 0.6779661  0.71186441 0.74576271 0.69491525]